/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ['class'],
  content: [
    "./src/**/*.{html,ts}",
  ],
  theme: {
    extend: {
      colors: {
        'primary': 'var(--app-primary)',
        'on-primary': 'var(--app-on-primary)',
        'primary-container': 'var(--app-primary-container)',
        'on-primary-container': 'var(--app-on-primary-container)',
        'primary-fixed': 'var(--app-primary-fixed)',
        'primary-fixed-dim': 'var(--app-primary-fixed-dim)',
        'on-primary-fixed': 'var(--app-on-primary-fixed)',
        'on-primary-fixed-variant': 'var(--app-on-primary-fixed-variant)',
        'secondary': 'var(--app-secondary)',
        'on-secondary': 'var(--app-on-secondary)',
        'secondary-container': 'var(--app-secondary-container)',
        'on-secondary-container': 'var(--app-on-secondary-container)',
        'secondary-fixed': 'var(--app-secondary-fixed)',
        'secondary-fixed-dim': 'var(--app-secondary-fixed-dim)',
        'on-secondary-fixed': 'var(--app-on-secondary-fixed)',
        'on-secondary-fixed-variant': 'var(--app-on-secondary-fixed-variant)',
        'tertiary': 'var(--app-tertiary)',
        'on-tertiary': 'var(--app-on-tertiary)',
        'tertiary-container': 'var(--app-tertiary-container)',
        'on-tertiary-container': 'var(--app-on-tertiary-container)',
        'tertiary-fixed': 'var(--app-tertiary-fixed)',
        'tertiary-fixed-dim': 'var(--app-tertiary-fixed-dim)',
        'on-tertiary-fixed': 'var(--app-on-tertiary-fixed)',
        'on-tertiary-fixed-variant': 'var(--app-on-tertiary-fixed-variant)',
        'error': 'var(--app-error)',
        'on-error': 'var(--app-on-error)',
        'error-container': 'var(--app-error-container)',
        'on-error-container': 'var(--app-on-error-container)',
        'surface-dim': 'var(--app-surface-dim)',
        'surface': 'var(--app-surface)',
        'surface-bright': 'var(--app-surface-bright)',
        'surface-container-lowest': 'var(--app-surface-container-lowest)',
        'surface-container-low': 'var(--app-surface-container-low)',
        'surface-container': 'var(--app-surface-container)',
        'surface-container-high': 'var(--app-surface-container-high)',
        'surface-container-highest': 'var(--app-surface-container-highest)',
        'on-surface': 'var(--app-on-surface)',
        'on-surface-variant': 'var(--app-on-surface-variant)',
        'outline': 'var(--app-outline)',
        'outline-variant': 'var(--app-outline-variant)',
        'inverse-surface': 'var(--app-inverse-surface)',
        'inverse-on-surface': 'var(--app-inverse-on-surface)',
        'inverse-primary': 'var(--app-inverse-primary)',
        'scrim': 'var(--app-scrim)',
        'shadow': 'var(--app-shadow)',
      },
      borderRadius: {
        'sys-sm': 'var(--app-sys-shape-corner-small)',
        'sys-md': 'var(--app-sys-shape-corner-medium)',
        'sys-lg': 'var(--app-sys-shape-corner-large)',
        'sys-xl': 'var(--app-sys-shape-corner-extra-large)',
      },
      maxWidth: {
        '2.5xl': '45rem',
      },
    },
  },
  plugins: [],
}

